version: "3.9"
   
services:
  satisfactory:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "80:80"
    command: "npm start"
    env_file:
      - .env